### ISSUE TITLE
Navigation Clarity suggestions

### ISSUE THREAD

**Issue by sjlawton** [chrisvfritz/codekwondo#3]
Just a couple suggestions about the overall navigation.

"Add Showcase" and the link to view showcases being a title is a bit confusing, it seems like a place you might submit screenshots after turning in the project

I would suggest changing it to two separate buttons at the bottom and calling them Submit Project and View Projects, or something like that.

The other thing that I noticed is that when reading through the 2d slides, things are organized with broad topics in vertical columns. Since most people read each topic in order, this leads to reading the content top-to-bottom, left-to-right. You may want to consider changing them to be topics in each row, so you read them left-to-right, top-to-bottom. Then you can make the right arrow direct you to the next topic when you reach the end of one. This leads to a slide set than can be read like a traditional powerpoint by just pressing right, and allows you to jump to previous/next topic by hitting up/down.

**Comment by chrisvfritz** [comment]
Thanks for these! I agree on all points. I'll update the showcase buttons right before our next class (after spring break).

Regarding the slides, from the data I'm collecting, many people actually seem to prefer viewing the slides completely vertically on GitHub ([like this for example](https://gist.github.com/chrisvfritz/084a9ba04eb183e92ab3)), so I'm considering ditching the slide format altogether. I'm still not sure how I'd organize that on the page though. Something nice about the slides is they have a fixed aspect ratio. I'll play around though. Either way, the multi-dimensionality has definitely proven more confusing than helpful.

**Comment by chrisvfritz** [comment]
I believe [this commit](https://github.com/chrisvfritz/codekwondo/commit/2445c354965bb3aa68a2f984832d2f42371e3bfa) should fix the project/showcase buttons being confusing! It's live on Codekwondo now, so let me know if it resolves the confusion.

For the slides problem, I'm updating all future slides (including this week's) to only be 1-dimensional. They're unfortunately 1-dimension from top-to-bottom, rather than left-to-right, as making it left-to-right would break previous slides. Over the summer when I rewrite most of Codekwondo, I'll probably overhaul these to get rid of the slides altogether and just show instructions in a nicely formatted list - as most people seem to prefer that anyway.
